### ISSUE TITLE
ARM node-gyp configure error

### ISSUE THREAD

**Issue by medonomator** [farafonov-alexey/node-atol-wrapper#10]
Доброго дня. Никак не могу собрать под arm raspberry. Если собираю на версиях ниже 12 выдает такое 

![Screenshot from 2019-12-24 14-13-13](https://user-images.githubusercontent.com/15996156/71410741-885c9300-2657-11ea-8037-04f6ff9d0ff0.png)
А если на 12 и выше то такая 

![Screenshot from 2019-12-24 14-14-04](https://user-images.githubusercontent.com/15996156/71410778-b17d2380-2657-11ea-89aa-26417e5a2b8f.png)

Что-то с питоном, никак не могу понять в чем причина...

**Comment by farafonov-alexey** [comment]
Привет, @medonomator.
Предполагается, что команда `node -e "console.log(process.arch)"` выполнится node и заполнит переменную arch в процессе сборки, наверное node по какой-то причине не смогла ее выполнить.
Затем данная переменная проверяется на равенство ia32 или x64 (думаю node под arm такое не вернет, а вернет что-то типа 'arm') и копируются соответствующие скомпилированные библиотеки в папку сборки (libfptr10 и др.)
В настоящий момент скомпилированных библиотек под arm в проекте нет и я не в курсе есть ли они в ДТО.

**Comment by maxvgi** [comment]
Всем привет.

Я библиотекой изначально пользовался исключительно под arm, никаких проблем при сборке не было. Просто изначально поставил deb-пакет библиотекой от Атол.

И дальше `npm install node-atol-wrapper`

Правда, версия `node-atol-wrapper` тогда была 0.0.15. В настоящий момент возможности проверить нет.

**Comment by medonomator** [comment]
Получилось собрать под arm, но теперь выдает Error 9 [ Способ связи с ККТ не поддерживается ]. Будто устройство просто не видит Атол, буду разбираться...

**Comment by maxvgi** [comment]
> Получилось собрать под arm, но теперь выдает Error 9 [ Способ связи с ККТ не поддерживается ]. Будто устройство просто не видит Атол, буду разбираться...

Если я правильно помню, то я сначала зашел в настройки кассы через графическую утилиту и выставил, что коннект с ней будет по USB.

Ну и в коде образно говоря так:
```
const connectionConfig = {Port: 1}; //usb
const settings = this.driver.getSettings();

for(let i in connectionConfig) {
   settings[i] = connectionConfig[i];
}

this.driver.setSettings(settings);
this.driver.open();
```

**Comment by medonomator** [comment]
Спасибо, все заработало. Могу сделать пул реквест с обновленным binding.gyp ? Хочу добавить условие для arm и файлы подсунуть

**Comment by farafonov-alexey** [comment]
@medonomator you are welcome!

**Comment by farafonov-alexey** [comment]
@medonomator, конечно

**Comment by maxvgi** [comment]
А кстати хороший вопрос. Посмотрел, в моей версии в binding.gyp - для linux не было никаких действий, поэтому с компиляцией под arm не было никаких вопросов.

Для windows - согласен, там с установкой и компиляцией отдельная история.

А нужно ли копирование so-файлов для linux? У вас библиотеки установлены не system-wide?

**Comment by medonomator** [comment]
Не могу запушить ветку, нет доступа 403

**Comment by medonomator** [comment]
> А кстати хороший вопрос. Посмотрел, в моей версии в binding.gyp - для linux не было никаких действий, поэтому с компиляцией под arm не было никаких вопросов.
> 
> Для windows - согласен, там с установкой и компиляцией отдельная история.
> 
> А нужно ли копирование so-файлов для linux? У вас библиотеки установлены не system-wide?

Совсем не понимаю о чем вы ) Под arm нужны файлы из ДТО, сейчас таковых нету

**Comment by maxvgi** [comment]
> Не могу запушить ветку, нет доступа 403

Нужно сначала склонировать этот репозитарий, потом запушить изменения в свой репозитарий, а затем уже создавать pull request.

**Comment by medonomator** [comment]
Запушить изменения в свой репозиторий ??  Вы о чем ?)) Я склонировал репу, создал ветку, сделал работу, после этого хочу запушить и вылетает 403

**Comment by maxvgi** [comment]
> Запушить изменения в свой репозиторий ?? Вы о чем ?)) Я склонировал репу, создал ветку, сделал работу, после этого хочу запушить и вылетает 403

Да, простите, оговорился - не склонировать, а форкнуть.
Вы пытаетесь запушить коммит в чужой репозитарий, куда у вас нет прав на запись.

[Инструкция в картинках](https://rustycrate.ru/%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B0/2016/03/07/contributing.html) как делать pull request

**Comment by medonomator** [comment]
Ок, теперь понял, благодарю!

**Comment by maxvgi** [comment]
> Совсем не понимаю о чем вы ) Под arm нужны файлы из ДТО, сейчас таковых нету

Вы же непосредственно из-под raspberry собираете?

Скачал свежий драйвер ККТ, это zip-архив в 395 Мб. В нём по пути `/10.6.1.0/installer/deb/` лежат собранные пакеты для debian-based дистрибутивов. Закидываем пакет `libfptr10_10.6.1.0_armhf.deb` в raspberry, устанавливаем - `dpkg -i libfptr10_10.6.1.0_armhf.deb`

Всё, библиотеки установлены в систему по стандартным путям и доступны. После этого сборка проходит без лишних вопросов, ничего никуда копировать не надо.

Хотя иной подход тоже имеет место быть, мне просто ближе установка софта через пакеты.

**Comment by medonomator** [comment]
Такой вариант не подходит, даже если проделать все эти операции, в момент установки пакета npm i node-atol-wrapper выдает `gyp: Call to 'node -e "console.log(process.arch)"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp`
что говорит о том, что он может найти условия в .gyp под текущую архитектуру

**Comment by medonomator** [comment]
Очень интересно как вы умудрились собрать под rasperry если в .gyp нет такова условия)

**Comment by maxvgi** [comment]
А какие там условия?

В .gyp описаны дополнительные операции, которые требуется выполнить для сборки под конкретную платформу. Если библиотеки поставить нормально (через deb-пакет), то никакие операции не требуются, сборщик всё нормально сам собирает.

Я в своём пулл-реквесте [вообще удалял копирование файлов для линукса](https://github.com/farafonov-alexey/node-atol-wrapper/commit/f364c6ed529df9053abeebef862b588e6a95a581#diff-21e418851ae48f9b11907837add9e39a). Потому что после установки библиотеки ни на моем рабочем компе (x64), ни на raspberry (armhf) никакой магии в .gyp не требовалось.

Только сейчас увидел, что, оказывается, библиотеки из дистрибутива содержатся в этом репозитарии =) Ну да, возможно это и правда оптимальное решение - пользователю в этом случае даже не нужно знать, что есть какой-то драйвер от Атол.

В общем да, диалог продолжать смысла нет, теперь это больше похоже будет на холивар )

**Comment by farafonov-alexey** [comment]
> Спасибо, все заработало. Могу сделать пул реквест с обновленным binding.gyp ? Хочу добавить условие для arm и файлы подсунуть

@medonomator, желание еще не пропало?

**Comment by squalsoft** [comment]
Смотрю, что pull-request так и не сделали?

**Comment by squalsoft** [comment]
process.arc = arm

**Comment by farafonov-alexey** [comment]
#17
