### ISSUE TITLE
Подключение linux

### ISSUE THREAD

**Issue by Vladqqw** [farafonov-alexey/node-atol-wrapper#12]
Огромное спасибо за модуль, интегрировали на windows без проблем.

Вот с linux не можем подключиться:
Не через USB: 
```
{
    ...
    Port: 1, // USB
    UsbDevicePath: "auto",
    ...
}
```
Ни через COM порт:
```
{
    ...
    Port: 0, // COM
    UsbDevicePath: "/dev/ttyACM0", // тут ккт
    ...
}
```
Выбрасывает ошибку
`Error 4 [ Порт недоступен ]`

Linux с коробки не чего не устанавливали, возможно что-то нужно устанавливать или указывать дополнительные настройки, можете подсказать, буду признателен, спасибо.

**Comment by farafonov-alexey** [comment]
Добрый день, ДТО под linux работает с этим устройством? Вполне может быть проблема в правах доступа к порту.

**Comment by Vladqqw** [comment]
Вы правы, благодарю, проблема была именно в правах доступа к порту.
