### ISSUE TITLE
build windows ia32 "error : undefined symbol"

### ISSUE THREAD

**Issue by Vladqqw** [farafonov-alexey/node-atol-wrapper#13]
Добрый день.

Ошибка при сборки модуля для ia32 на windows
Собираю через nw-gyp v3.6.5
node -v v14.0.0

Подскажите пожалуйста в чем возможна ошибка?

```
lld-link : error : undefined symbol: __imp__libfptr_create [C:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by C:\project\node_modules\node-atol-wrapper\src\fptr10.cc:74
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::Create(class Nan::FunctionCallbackInfo<class v
  8::Value> const &))

lld-link : error : undefined symbol: __imp__libfptr_is_opened [C:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj
]
  >>> referenced by C:\project\node_modules\node-atol-wrapper\src\fptr10.cc:140
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::IsOpened(class Nan::FunctionCallbackInfo<class
   v8::Value> const &))
```
<details>
  <summary>Полный вывод</summary>
С:\project>nw-gyp rebuild --target=0.45.4 --arch=ia32 --msvs_version=2015 --directory=node_modules/node-atol-wrapper

gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.5
gyp info using node@14.0.0 | win32 | x64
gyp info chdir node_modules/node-atol-wrapper
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\project\\nwjs_mp\\node_modules\\node-atol-wrapper\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\PC\\.nw-gyp\\0.45.4\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\PC\\.nw-gyp\\0.45.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file="C:\\PC\\.nw-gyp\\0.45.4\\<(target_arch)\\node.lib"',
gyp info spawn args   '-Dnw_lib_file="C:\\PC\\.nw-gyp\\0.45.4\\<(target_arch)\\nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=D:\\project\\nwjs_mp\\node_modules\\node-atol-wrapper',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\project\\nwjs_mp\\node_modules\\node-atol-wrapper\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:CLToolExe=clang-cl.exe',
gyp info spawn args   '/p:LinkToolExe=lld-link.exe',
gyp info spawn args   '/p:CLToolPath=C:\\Roaming\\npm\\node_modules\\nw-gyp\\clang',
gyp info spawn args   '/p:LinkToolPath=C:\\Roaming\\npm\\node_modules\\nw-gyp\\clang',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
gyp info spawn args ]

Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".

  Copying С:\project\node_modules\node-atol-wrapper/src/win-x64/fptr10.lib to С:\project\node_modules\node-atol-wrapper\build\Re
  lease\\fptr10.lib
  Скопировано файлов:         1.
  Copying С:\project\node_modules\node-atol-wrapper/src/win-x64/msvcp140.dll to С:\project\node_modules\node-atol-wrapper\build\
  Release\\msvcp140.dll
  Скопировано файлов:         1.
  Copying С:\project\node_modules\node-atol-wrapper/src/win-x64/fptr10.dll to С:\project\node_modules\node-atol-wrapper\build\Re
  lease\\fptr10.dll
  Скопировано файлов:         1.

clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [С:\project\node_modules\node-atol-wrapp
er\build\node_atol_wrapper.vcxproj]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [С:\project\node_modules\node-atol-wrap
per\build\node_atol_wrapper.vcxproj]

### lld-link : error : undefined symbol: __imp__libfptr_create [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:74
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::Create(class Nan::FunctionCallbackInfo<class v
  8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_is_opened [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj
]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:140
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::IsOpened(class Nan::FunctionCallbackInfo<class
   v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_destroy [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:82
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::Destroy(class Nan::FunctionCallbackInfo<class
  v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_get_settings [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:89
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::GetSettings(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:93
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::GetSettings(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_set_settings [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:120
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::SetSettings(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_open [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:132
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::Open(class Nan::FunctionCallbackInfo<class v8:
  :Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_close [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:147
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::Close(class Nan::FunctionCallbackInfo<class v8
  ::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_set_param_str [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:168
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::ProcessJson(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_process_json [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:170
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::ProcessJson(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_get_param_str [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:174
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::ProcessJson(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:178
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::ProcessJson(class Nan::FunctionCallbackInfo<cl
  ass v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:270
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:274
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_set_param_int [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:249
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FnReport(class Nan::FunctionCallbackInfo<class
   v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:251
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FnReport(class Nan::FunctionCallbackInfo<class
   v8::Value> const &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:261
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_report [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:253
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FnReport(class Nan::FunctionCallbackInfo<class
   v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_fn_query_data [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:263
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_get_param_int [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:267
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_get_param_datetime [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\fptr10.cc:279
  >>>               Release\obj\node_atol_wrapper\fptr10.obj:(public: static void __cdecl Fptr10::FindLastDocument(class Nan::FunctionCallbackIn
  fo<class v8::Value> const &))

### lld-link : error : undefined symbol: __imp__libfptr_error_code [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxpro
j]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\utils.cc:19
  >>>               Release\obj\node_atol_wrapper\utils.obj:(bool __cdecl checkErrorString(void *, int, int &, class std::basic_string<char, str
  uct std::char_traits<char>, class std::allocator<char>> &))

### lld-link : error : undefined symbol: __imp__libfptr_error_description [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper
.vcxproj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\utils.cc:22
  >>>               Release\obj\node_atol_wrapper\utils.obj:(bool __cdecl checkErrorString(void *, int, int &, class std::basic_string<char, str
  uct std::char_traits<char>, class std::allocator<char>> &))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\utils.cc:26
  >>>               Release\obj\node_atol_wrapper\utils.obj:(bool __cdecl checkErrorString(void *, int, int &, class std::basic_string<char, str
  uct std::char_traits<char>, class std::allocator<char>> &))

### lld-link : error : undefined symbol: __imp__libfptr_set_param_str [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\json_worker.cc:9
  >>>               Release\obj\node_atol_wrapper\json_worker.obj:(public: virtual void __thiscall JsonWorker::Execute(void))

### lld-link : error : undefined symbol: __imp__libfptr_process_json [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\json_worker.cc:12
  >>>               Release\obj\node_atol_wrapper\json_worker.obj:(public: virtual void __thiscall JsonWorker::Execute(void))

### lld-link : error : undefined symbol: __imp__libfptr_get_param_str [С:\project\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\json_worker.cc:17
  >>>               Release\obj\node_atol_wrapper\json_worker.obj:(public: virtual void __thiscall JsonWorker::Execute(void))
  >>> referenced by С:\project\node_modules\node-atol-wrapper\src\json_worker.cc:21
  >>>               Release\obj\node_atol_wrapper\json_worker.obj:(public: virtual void __thiscall JsonWorker::Execute(void))

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\PC\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--
target=0.45.4" "--arch=ia32" "--msvs_version=2015" "--directory=node_modules/node-atol-wrapper"
gyp ERR! cwd С:\project\node_modules\node-atol-wrapper
gyp ERR! node -v v14.0.0
gyp ERR! nw-gyp -v v3.6.5
gyp ERR! not ok
</details>

PS для win x64, linux ia32 и linux x64, проблем не возникло, все собрал без проблем.

**Comment by farafonov-alexey** [comment]
Ошибка связана с тем что используется некорректный dll файл:

>Copying С:\project\node_modules\node-atol-wrapper/src/**win-x64**/fptr10.dll to >С:\project\node_modules\node-atol-wrapper\build\Release\fptr10.dll
>Скопировано файлов: 1.

Что происходит из-за
>gyp info using node@14.0.0 | win32 | **x64**

и потому что для определения архитектуры используется скрипт в binding.gyp:
`'arch': '<!(node -e "console.log(process.arch)")'`

Отсюда:
1) если node x86 - будет работать из коробки
2) если хочется собрать в такой конфигурации - требуется изучить как прокинуть в binding.gyp вот эту переменную arch
>nw-gyp rebuild --target=0.45.4 **--arch=ia32** --msvs_version=2015 --

**Comment by Vladqqw** [comment]
Благодарю за помощь.
Изменил в файле модуля архитектуру binding.gyp:
```
'arch': 'ia32'
```
