### ISSUE TITLE
Не собирается на Raspberry

### ISSUE THREAD

**Issue by squalsoft** [farafonov-alexey/node-atol-wrapper#16]
Добрый день! Сегодня попробовал поставить кассу на Raspberry, но к сожалению, не ставится ваш модуль через npm install. Вылетает ошибка gyp. Я так понял, что это связано с архитектурой arm, которой нет в настройках?

**Comment by farafonov-alexey** [comment]
Посмотрите этот issue #10

**Comment by squalsoft** [comment]
Я так понял, что pull-request этот чувак там так и не сделал. Надо добавить библиотеки под raspberry. Ща попробую добавить.

**Comment by farafonov-alexey** [comment]
Да дело до PR так и не дошло)

**Comment by squalsoft** [comment]
Можете сделать новую версию? Я залил PR.

**Comment by farafonov-alexey** [comment]
#17
