### ISSUE TITLE
Не передаются данные в ОФД

### ISSUE THREAD

**Issue by squalsoft** [farafonov-alexey/node-atol-wrapper#18]
Здравствуйте! Можете подсказать, почему при работе в Linux не передаются данные в ОФД? Если подключить кассу к тестовому приложению драйвера в Windows, то данные передаются, а в Linux ни в какую не хотят передаваться. Я использую способ передачи данных по EoT. Настройки такие:
settings.Port = 0; // com
settings.OfdChannel = 1; // eot
settings.ComFile = "/dev/ttyACM0";

Может, eot не работает через COM?

**Comment by squalsoft** [comment]
В mac os, кстати, аналогичная ситуация.

**Comment by farafonov-alexey** [comment]
Добрый день, вопрос скорее к самому ДТО, а не к обертке. Из простого: данные в ОФД передаются только если девайс находится во включенном состоянии. Также в ДТО есть логи ОФД можно посмотреть в них.

**Comment by squalsoft** [comment]
А где можно посмотреть логи?

**Comment by squalsoft** [comment]
Нашёл в ~/.atol

**Comment by squalsoft** [comment]
В логах всё чисто, никаких ошибок нет. Файл ofd.log вообще пустой. Может, какой-то библиотеки не хватает? Так как в windows данные отправляются нормально.

**Comment by squalsoft** [comment]
Также не понятно, где брать параметры для настроек драйвера (settings). Используются некие цифры, о которых в документации АТОЛ ничего нет.

**Comment by farafonov-alexey** [comment]
Думаю из оф. документации - [driver_settings](http://integration.atol.ru/api/#driver_settings)
И файла libfptr10.h.  Например [тут](https://github.com/farafonov-alexey/node-atol-wrapper/blob/master/src/libfptr10.h#L719) enum со списком типов подключения.

**Comment by squalsoft** [comment]
Благодарю. Это действительно важная информация по настройке данного драйвера.
Настройка settings.OfdChannel = 2; Решила мою проблему. Я думал, что это канал передачи данных EoU/EoT, а оказалось другое:
enum libfptr_ofd_channel
{
    LIBFPTR_OFD_CHANNEL_NONE = 0,
    LIBFPTR_OFD_CHANNEL_USB,
    LIBFPTR_OFD_CHANNEL_PROTO,
    LIBFPTR_OFD_CHANNEL_AUTO = LIBFPTR_OFD_CHANNEL_PROTO
};
