### ISSUE TITLE
Вылетает ошибка is not a valid Win32 application

### ISSUE THREAD

**Issue by muaddip01** [farafonov-alexey/node-atol-wrapper#19]
- Preparing native dependencies: 0 / 1gyp info find Python using Python version 3.9.2 found at "C:\Python39\python.exe"
\ Preparing native dependencies: 0 / 1gyp info find VS using VS2017 (15.9.28307.1440) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-atol-wrapper\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\muadd\\.electron-gyp\\12.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\muadd\\.electron-gyp\\12.0.1',
gyp info spawn args   '-Dnode_gyp_dir=D:\\git_evator\\cashreg\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\muadd\\\\.electron-gyp\\\\12.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\git_evator\\cashreg\\node_modules\\node-atol-wrapper',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-atol-wrapper\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
| Preparing native dependencies: 0 / 1gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64',
gyp info spawn args   map: [Function (anonymous)]
gyp info spawn args ]
/ Preparing native dependencies: 0 / 1Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
\ Preparing native dependencies: 0 / 1  Copying D:\git_evator\cashreg\node_modules\node-atol-wrapper/src/win-x64/fptr10.dll to D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\
  Скопировано файлов:         1.
  Copying D:\git_evator\cashreg\node_modules\node-atol-wrapper/src/win-x64/msvcp140.dll to D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\
  Скопировано файлов:         1.
  Copying D:\git_evator\cashreg\node_modules\node-atol-wrapper/src/win-x64/fptr10.lib to D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\
  Скопировано файлов:         1.
- Preparing native dependencies: 0 / 1  index.cc
/ Preparing native dependencies: 0 / 1c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1650): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1632): note:  см. объявление "v8::Module::ResolveCallback"
\ Preparing native dependencies: 0 / 1  fptr10.cc
/ Preparing native dependencies: 0 / 1c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1650): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1632): note:  см. объявление "v8::Module::ResolveCallback"
/ Preparing native dependencies: 0 / 1  utils.cc
\ Preparing native dependencies: 0 / 1c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1650): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1632): note:  см. объявление "v8::Module::ResolveCallback"
\ Preparing native dependencies: 0 / 1  json_worker.cc
| Preparing native dependencies: 0 / 1c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1650): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\muadd\.electron-gyp\12.0.1\include\node\v8.h(1632): note:  см. объявление "v8::Module::ResolveCallback"
| Preparing native dependencies: 0 / 1  win_delay_load_hook.cc
/ Preparing native dependencies: 0 / 1     ╤ючфрхЄё  сшсышюЄхър D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\node_atol_wrapper.lib ш юс·хъЄ D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\node_atol_wrapper.exp
- Preparing native dependencies: 0 / 1  ╤ючфрэшх ъюфр
- Preparing native dependencies: 0 / 1  All 757 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  ╤ючфрэшх ъюфр чртхЁ°хэю
| Preparing native dependencies: 0 / 1  node_atol_wrapper.vcxproj -> D:\git_evator\cashreg\node_modules\node-atol-wrapper\build\Release\\node_atol_wrapper.node
- Preparing native dependencies: 1 / 2gyp info find Python using Python version 3.9.2 found at "C:\Python39\python.exe"
| Preparing native dependencies: 1 / 2gyp info find VS using VS2017 (15.9.28307.1440) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\shtrih-m-js\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\muadd\\.electron-gyp\\12.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\muadd\\.electron-gyp\\12.0.1',
gyp info spawn args   '-Dnode_gyp_dir=D:\\git_evator\\cashreg\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\muadd\\\\.electron-gyp\\\\12.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\git_evator\\cashreg\\node_modules\\shtrih-m-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\git_evator\\cashreg\\node_modules\\shtrih-m-js\\build',

App threw an error during load
Error: node-loader:
Error: D:\git_evator\cashreg\.webpack\main/12b0a5c2780f1aae5c7e704395e33c4a.node is not a valid Win32 application.
D:\git_evator\cashreg\.webpack\main/12b0a5c2780f1aae5c7e704395e33c4a.node
    at Object.<anonymous> (D:\git_evator\cashreg\.webpack\main\index.js:6940:9)
    at Object../node_modules/node-atol-wrapper/build/Release/node_atol_wrapper.node (D:\git_evator\cashreg\.webpack\main\index.js:6943:30)
    at __webpack_require__ (D:\git_evator\cashreg\.webpack\main\index.js:21:30)
    at Object../node_modules/node-atol-wrapper/bindings.js (D:\git_evator\cashreg\.webpack\main\index.js:6923:17)
    at __webpack_require__ (D:\git_evator\cashreg\.webpack\main\index.js:21:30)
    at Object../src/native/atolIpc.ts (D:\git_evator\cashreg\.webpack\main\index.js:19006:12)
    at __webpack_require__ (D:\git_evator\cashreg\.webpack\main\index.js:21:30)
    at Object../src/index.ts (D:\git_evator\cashreg\.webpack\main\index.js:18713:17)
    at __webpack_require__ (D:\git_evator\cashreg\.webpack\main\index.js:21:30)
    at D:\git_evator\cashreg\.webpack\main\index.js:85:18
webpack built 30cb827c62990537f151 in 29423ms

Это не единственный модуль который у меня собирается, с остальными все нормально.

**Comment by farafonov-alexey** [comment]
#13

**Comment by muaddip01** [comment]
Можно закрывать, проблема была в electron-forge,
необходимо было закомментировать строки в webpack.rules.js
// Add support for native node modules
  // {
  //   test: /\.node$/,
  //   use: 'node-loader',
  // },
