### ISSUE TITLE
Как использовать этот пакет?

### ISSUE THREAD

**Issue by squalsoft** [farafonov-alexey/node-atol-wrapper#2]
Добрый день! Хотелось бы какой-то пример, как использовать этот пакет? Не получается подключить его в существующий проект.
Я так понял, что надо вместо const w = require('./bindings'); в файле index.js у себя подключать так:
const w = require("node-atol-wrapper");
А далее использовать, как и в index.js?

**Comment by farafonov-alexey** [comment]
Добрый день. Да, конечно, именно так.

Меняется только:
`const wrapperAtol = require('node-atol-wrapper');`

Затем создается объект:
`const fptr = new wrapperAtol.Fptr10();`

И у fptr вызываются функции, описанные в [README](https://github.com/farafonov-alexey/node-atol-wrapper/blob/master/README.md) (create, destroy, ...)
