### ISSUE TITLE
Поддержка версии 10.9.0.0

### ISSUE THREAD

**Issue by val-ar** [farafonov-alexey/node-atol-wrapper#20]
Здравствуйте. Вышла новая версия драйвера 10.9.0.0 с поддержкой ФФД 1.2.
Подскажите когда обновите пакет?

**Comment by farafonov-alexey** [comment]
[v0.0.21](https://github.com/farafonov-alexey/node-atol-wrapper/releases/tag/v0.0.21)

**Comment by val-ar** [comment]
Спасибо за оперативность.
