### ISSUE TITLE
Не собирается на node 12

### ISSUE THREAD

**Issue by Al-Rozhkov** [farafonov-alexey/node-atol-wrapper#5]
Во-первых, огромное спасибо за модуль 👍 

К сожалению, не удается запустить проект на node 12. Похоже, что все ломается на стадии `node-qyp rebuild`.

Если вернуться на node 10, все запускается.

**Comment by farafonov-alexey** [comment]
Привет! Почему-то не было оповещения об Issue. 
Постараюсь посмотреть, в чем проблема.

**Comment by farafonov-alexey** [comment]
@Al-Rozhkov Можно попроверять, Travis вроде собрал.

**Comment by Al-Rozhkov** [comment]
Спасибо огромное! К сожалению, раньше 8-го числа не смогу проверить.

**Comment by Al-Rozhkov** [comment]
@farafonov-alexey, а можно подсказку, как протестировать последний коммит? У меня приложение на electron. Простое копирование кода в `node_modules/node-atol-wrapper` не решило проблему, сборка не завершается.

Когда делается релиз, в модуле появляется папка `build`, в репозитории, естественно, этой папки нет. Как собрать модуль самому? `npm rebuild` папку `build` не собрал.

**Comment by farafonov-alexey** [comment]
@Al-Rozhkov, склонировать этот репозиторий. Затем в папке с репозиторем:

```
yarn
yarn start
```

Можно подредактировать index.js для своего теста и потом опять `yarn start`.
Версия с этим изменением еще не выложена в npm, думаю из-за этого сборка не проходит.

**Comment by Al-Rozhkov** [comment]
Появилась ошибка на первом этапе `yarn`: `невозможно преобразовать аргумент 1 из "v8::Isolate *" в "v8::Local"`

```
...\node-atol-wrapper-master\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: "v8::MaybeLocal  8::Function> v8::Function::New(v8::Local,v8::FunctionCallback,v8::  Local,int,v8::ConstructorBehavior,v8::SideEffectType)": невозможно преобразовать аргумент 1 из "v8::Isolate *" в "v8::Local" (компилируется исходный файл ..\src\index.cc) [...\node-atol-wrapper-master\node-atol-wrapper-master\build\node_atol_wrapper.vcxproj]
```

Win 10, node 12.13.0, yarn 1.19.1.

**Comment by farafonov-alexey** [comment]
Ок, я посмотрю.

**Comment by farafonov-alexey** [comment]
После #7  должно работать.
@Al-Rozhkov, посмотри.

**Comment by Al-Rozhkov** [comment]
Спасибо огромное, заработало! 👍 
С нетерпением ждем релиз.

**Comment by farafonov-alexey** [comment]
Выложил версию 0.0.16
