### ISSUE TITLE
Обновление ДТО до 10.6.0.0

### ISSUE THREAD

**Issue by Asp3ctus** [farafonov-alexey/node-atol-wrapper#8]
Добрый день

Спасибо за модуль!

Планируется ли обновление до ДТО 10.6.0.0 ?

**Comment by farafonov-alexey** [comment]
Добрый день, @Asp3ctus.
Выложил  версию [0.0.17](https://github.com/farafonov-alexey/node-atol-wrapper/tree/v0.0.17)

**Comment by Asp3ctus** [comment]
Огромное спасибо, сегодня по тестирую на винде и линуксе и закрою issue.
Небольшое замечание по поводу версий модуля, думаю что лучше придерживаться semver, мало ли у кого какие глюки могут возникнуть из за того что модуль сам обновится при npm i
так что лучше на будущее перейти на 0.X.Y версию.. и увеличивать X если добавляются новые фичи или обновляется ДТО ... но это лишь предложение :)

**Comment by Al-Rozhkov** [comment]
0.0.17 работает отлично. Тем временем вышел драйвер 10.6.1.0 )

**Comment by farafonov-alexey** [comment]
#14
