### ISSUE TITLE
Есть ли возможность подключить библиотеки для MacOs

### ISSUE THREAD

**Issue by squalsoft** [farafonov-alexey/node-atol-wrapper#9]
Вроде, у драйвера есть библиотеки для мака. Я веду разработку ПО в MacOs. Хотел бы узнать, есть ли возможность подключить маковские библиотеки в пакет?

**Comment by farafonov-alexey** [comment]
Думаю, что такая возможность действительно есть. Но в настоящий момент есть острая нехватка со временем. Pull requests are welcome =)

**Comment by phwb** [comment]
Привет, создал ПР https://github.com/farafonov-alexey/node-atol-wrapper/pull/14 на эту тему

**Comment by farafonov-alexey** [comment]
Выложил версию [0.0.19](https://github.com/farafonov-alexey/node-atol-wrapper/releases/tag/v0.0.19)
